# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
    build:
        name: CI
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 17.x, 18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: Checkout Repository & Submodules
              uses: actions/checkout@v2
              with:
                submodules: recursive
            - name: Setup Node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Typecheck 
              run: yarn typecheck
            - name: Lint 
              run: yarn lint
            - name: Test
              run: yarn test
